#!/usr/bin/env php
<?php

$files = [
	__DIR__.'/../../autoload.php',
	__DIR__.'/../autoload.php',
	__DIR__.'/vendor/autoload.php'
];

foreach ($files as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

use Danj\Spotify\Application;

$app = new Application();

$app->start([
    Danj\Spotify\Commands\Auth\Login::class,
	Danj\Spotify\Commands\Auth\Logout::class,
    Danj\Spotify\Commands\Playback\Pause::class,
    Danj\Spotify\Commands\Playback\Play::class,
    Danj\Spotify\Commands\Playback\Next::class,
    Danj\Spotify\Commands\Playback\Previous::class,
    Danj\Spotify\Commands\Playback\Current::class

]);

$application->run();
